#' Decidua Single Cell RNA-seq Dataset 
#'
#' A subset of log normalized decidua scRNA-seq dataset generated by \href{https://www.nature.com/articles/s41586-018-0698-6}{Vento-tormo et al. 2018 Nature}.
#' It contains the 726 EVT, 953 dS2, 788 dNK1, and 533 dM1 cells.
#' @format A sparse matrix with logTPM normalized transcript counts of 947 rows (ligand/receptor genes) and 3000 columns (cells).
#' @source \url{https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6701/}
"decidua"

#' Decidua Single Cell RNA-seq Annotation Metadata 
#'
#' A subset of decidua scRNA-seq metadata generated by \href{https://www.nature.com/articles/s41586-018-0698-6}{Vento-tormo et al. 2018 Nature}.
#' It contains the 726 EVT, 953 dS2, 788 dNK1, and 533 dM1 cells.
#' @format A data frame with 3000 rows (cells) and 4 columns (attributes):
#' \describe{
#'   \item{Fetus}{fetus ID}
#'   \item{location}{organ name}
#'   \item{final_cluster}{cluster ID}
#'   \item{annotation}{cell type annotation}
#' }
#' @source \url{https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6701/}
"decidua.annotation"

#' CellPhoneDB Database
#'
#' A preloaded \href{https://www.cellphonedb.org/}{CellPhoneDB} database of ligand-receptor interaction pairs.
#' @format A data frame with 1574 rows (ligand-receptor pairs) and 15 columns (attributes):
#' \describe{
#'   \item{genename_a, genename_b}{interaction partner gene names}
#'   \item{id_cp_interaction}{CellPhoneDB interaction id}
#'   \item{partner_a, partner_b}{interaction partner uniprot ids}
#'   \item{protein_name_a, protein_name_b}{interaction partner protein names}
#'   \item{annotation_strategy}{annotation strategy}
#'   \item{source}{annotation strategy}
#'   \item{subunit_a_1, subunit_a_2, subunit_a_3}{interaction partner a complex subunits}
#'   \item{subunit_b_1, subunit_b_2, subunit_b_3}{interaction partner b complex subunits} 
#' }
#' @source \url{https://www.cellphonedb.org/}
"cellphonedb"