# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CosineNormSparse <- function(data, display_progress = TRUE) {
    .Call('_scMatchmaker_CosineNormSparse', PACKAGE = 'scMatchmaker', data, display_progress)
}

CosineNorm <- function(data, display_progress = TRUE) {
    .Call('_scMatchmaker_CosineNorm', PACKAGE = 'scMatchmaker', data, display_progress)
}

